apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app: argocd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      containers:
      - name: argocd-server
        image: argoproj/argocd:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: argocd-tls
          mountPath: /app/config/argocd-secret
          readOnly: true
      volumes:
      - name: argocd-tls
        secret:
          secretName: argocd-secret
